import QuestionnaireForm from "@/components/QuestionnaireForm/QuestionnaireForm";
import Head from "next/head";
import React, { useState } from "react";

const questionsArray = [
  {
    question: "How do you travel to work ?",
    answers: [
      { answer: "Car / Motorbike", points: 0 },
      { answer: "Car Share", points: 1 },
      { answer: "Bus", points: 2 },
      { answer: "Walk / Cycle", points: 3 },
    ],
  },
  {
    question: "How do you travel to work ?",
    answers: [
      { answer: "Car / Motorbike", points: 0 },
      { answer: "Car Share", points: 1 },
      { answer: "Bus", points: 2 },
      { answer: "Walk / Cycle", points: 3 },
    ],
  },
];

export default function Questionnaire() {
  const [questionStep, setQuestionStep] = useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center min-h-screen">
        <QuestionnaireForm
          questionsArray={questionsArray}
          questionStep={questionStep}
        />
      </main>
    </>
  );
}
